pipeline:
  name: Avinash s
  identifier: Avinash_s
  projectIdentifier: harness1
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Avinash_s
        build: <+input>
  stages:
    - stage:
        name: clone_repository
        identifier: clone_repository
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Windows
            arch: Arm64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: Avinash_s
                    cloneDirectory: .harness/Avinash_s.yaml
                    build:
                      type: branch
                      spec:
                        branch: main
